Repository FIWARE/kong-plugins-fiware, pull requests merged in 2022-06, with the labels that each got.

#1 Ci
  .github/workflows/check.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  kong-plugin-auth-endpoint-config-ishare/rockspec.mustache
  kong-plugin-ngsi-ishare-policies/rockspec.mustache
Labels: patch

#4 build rocks
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  kong-plugin-auth-endpoint-config-ishare/rockspec.mustache
  kong-plugin-ngsi-ishare-policies/rockspec.mustache
Labels: patch

#5 plugins are required
  .github/workflows/release.yml
Labels: patch

#6 Increase version of lua library
  kong-plugin-auth-endpoint-config-ishare/rockspec.mustache
  kong-plugin-ngsi-ishare-policies/rockspec.mustache
Labels: bug, enhancement, patch

#7 Update README.md
  README.md
Labels: patch

#9 Adding test suite
  .github/workflows/test.yml
  kong-plugin-auth-endpoint-config-ishare/spec/auth-endpoint-config-ishare/01-schema_spec.lua
  kong-plugin-auth-endpoint-config-ishare/spec/auth-endpoint-config-ishare/02-plugin_spec.lua
  kong-plugin-ngsi-ishare-policies/spec/ngsi-ishare-policies/01-schema_spec.lua
  kong-plugin-ngsi-ishare-policies/spec/ngsi-ishare-policies/02-plugin_spec.lua
  pongo/Dockerfile
  pongo/build.sh
  pongo/pongo-docker.sh
  run_tests.sh
Labels: minor
